### ISSUE TITLE
Dev dependencies in prod dependencies.

### ISSUE THREAD

**Issue by gaugau3000** [hyperliquid-dex/hyperliquid-python-sdk#14]
Hi,

Why is there dev dependencies in requirements.txt like pytest ?

Many tks.

**Comment by gaugau3000** [comment]
Forget previous message and

Help to follow, transcript from discord.

gautier — Hier à 20:06
Oki, seems the requirements.txt is generated by Makefile when dev run make install. Not sure why the  requirements.txt is for, but ok (difficult to identify source of truth)
So pyproject.toml use poetry to install deps and
pytest and pytest-recording  shoudl not be in dependencies but in dev dependencie? 
ben_hl — Hier à 20:15
That sounds accurate. I haven't gotten a chance to try moving them and making sure everything still works. Should be able to get it done within the next day or two and release a new version of the sdk

see you.

**Comment by traderben** [comment]
This is now fixed in the latest version 0.1.19
