### ISSUE TITLE
market_close not working for API key users

### ISSUE THREAD

**Issue by jawilk** [hyperliquid-dex/hyperliquid-python-sdk#15]
Hi there,

the `market_close` method in the `Exchange` class fetches the user positions to determine size etc
https://github.com/hyperliquid-dex/hyperliquid-python-sdk/blob/67864cf979d3bbea2e964a99ecc0a1effb7bb911/hyperliquid/exchange.py#L232
if the `Exchange` class was initialized with an API key, `self.wallet.address` is the public address of the API wallet, which has no positions.

It may make sense to add an additional optional `main_account_address` variable in the exchange class?
```
class Exchange(API):
     def __init__(
        ...,
        main_account_address: Optional[str] = None,
    ):
    # ...
    self.main_account_address = main_account_address
    # ...

    def market_close(...):
        address = self.main_account_address if self.main_account_address not None else self.wallet.address
        positions = self.info.user_state(address)["assetPositions"]
        if positions is None:
            print("No open positions, make sure your account has open positions or a main wallet address is set if you are using an API key.")
            return
```
```

**Comment by traderben** [comment]
Thanks for reporting. Yep, we'll either add an optional argument to exchange or to market_close. market_close also has issues when trading for a vault

**Comment by jawilk** [comment]
awesome thanks for the quick reply!

**Comment by traderben** [comment]
This has been fixed, sorry I forgot to update when we did so
