### ISSUE TITLE
SDK Disconnects after few mins of unactivity

### ISSUE THREAD

**Issue by cyborg3poch** [hyperliquid-dex/hyperliquid-python-sdk#21]
I am connecting HL with skip_ws=True . The problem which arises is that it disconnects after few minutes of connectivity.
Hoping to find a solution(workaround) to this issue

**Comment by traderben** [comment]
What do you mean by disconnect? If you are setting skip_ws=True, you shouldn't be creating a websocket connection so there shouldn't be anything to disconnect

**Comment by cyborg3poch** [comment]
nevermind
