### ISSUE TITLE
Can remove this cloid condition

### ISSUE THREAD

**Issue by sc0Vu** [hyperliquid-dex/hyperliquid-python-sdk#22]
I think this if condition can be removed (compare in `order_request_to_order_wire`): https://github.com/hyperliquid-dex/hyperliquid-python-sdk/blob/master/hyperliquid/exchange.py#L100

```PYTHON3
      if cloid:
            order["cloid"] = cloid
```

**Comment by traderben** [comment]
Yes, it does appear that code could be simplified. Is it causing any issues for you though?

**Comment by traderben** [comment]
Closing due to lack of response
