### ISSUE TITLE
Include USDC value on spotClearinghouseState balances

### ISSUE THREAD

**Issue by SitoCH** [hyperliquid-dex/hyperliquid-python-sdk#36]
Hi,
I know that is only the repository for the Python SDK and not for the API but I didn't find a better suited repository.
When accessing spotClearinghouseState (spot_user_state), the response contains only the token balances, it would be great to have also the current USDC value since it isn't exposed by any other mean.

Thanks

**Comment by traderben** [comment]
I recommend you use the api-traders channel in the hyperliquid discord to ask questions. The spot USDC token balances are returned in the spotClearinghouseState response. Perhaps your account doesn't have any USDC in which case it would be skipped as tokens that have no balances aren't returned
