### ISSUE TITLE
Deposit or Transfer Vault issue

### ISSUE THREAD

**Issue by IceCaptain0715** [hyperliquid-dex/hyperliquid-python-sdk#39]
Can't find any funcitons or signing transactions methods on Exchange class like transfer_vault although there is documentation for api in https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/exchange-endpoint.
Trying to fix the issues for my self with module customization.
But not sure for the parameters.
![image](https://github.com/hyperliquid-dex/hyperliquid-python-sdk/assets/151121761/7f0d5852-6aee-4cb8-9fea-ec97a878a2ce)

**Comment by traderben** [comment]
Yes I added the documentation because you asked about it in the discord yesterday and I replied there. Discord usually gets the fastest response. Please don't create additional tickets and issues for the same question it just creates additional work for the team

**Comment by IceCaptain0715** [comment]
Thanks for your reply.
Currently I am having issues on creating signature for the action.
 def transfer_vault(self, amount: int, vaultAddress: str, isDeposit: bool)
-> Any:
        timestamp = get_timestamp_ms()
        action = {"vaultAddress": vaultAddress, "usd": amount, "isDeposit":
isDeposit, "type": "vaultTransfer"}
        print(action)
        is_mainnet = self.base_url == MAINNET_API_URL
        signature = sign_vault_transfer_action(self.wallet, action,
is_mainnet)
        print(signature)
        return self._post_action(
            action,
            signature,
            timestamp,
        )

def sign_vault_transfer_action(wallet, action, is_mainnet):
    return sign_user_signed_action(
        wallet,
        action,
        [
            {"name": "hyperliquidChain", "type": "string"},
            {"name": "vaultAddress", "type": "string"},
            {"name": "isDeposit", "type": "bool"},
            {"name": "usd", "type": "uint64"},
        ],
        "HyperliquidTransaction:VaultTransfer",
        is_mainnet,
    )

I am not sure about //        "HyperliquidTransaction:VaultTransfer",//
because there is not detailed documentation about that.

**Comment by IceCaptain0715** [comment]
Yes, it is working.
