### ISSUE TITLE
what's the meaning of some coin symbols such as @1, @2 etc

### ISSUE THREAD

**Issue by chitown2016** [hyperliquid-dex/hyperliquid-python-sdk#44]
When I run the following code:

```python
import example_utils
from hyperliquid.utils import constants
address, info, exchange = example_utils.setup(base_url=constants.MAINNET_API_URL, skip_ws=True)
all_mids = info.all_mids()
hyperliquid_symbols = all_mids.keys()
```

In hyperliquid_symbols I see things like @1, @2 etc. What do these symbols mean? I cannot find them in the user interface..

**Comment by traderben** [comment]
https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/info-endpoint#perpetuals-vs-spot
