### ISSUE TITLE
User or API Wallet .. does not exist.

### ISSUE THREAD

**Issue by 8m0** [hyperliquid-dex/hyperliquid-python-sdk#54]
Can't find anything useful about the error on internet. I hope someone could guide me what could be the problem.

I get the error:

> L1 error: User or API Wallet 0x399129af1d8f5b030e00a3e15e68610a884bced6 does not exist.

Wallet address in the message always different when i call Place an order.

I tried using private key of my MetaMask wallet, then tried API wallet of Hyperliquid. Am i missing some important peace of info?

My technology is .NET written by me.

I tried also CCXT garbage mess C# code, copying parts of their code and after many hours of assembling the abomination it showed me the same message omg...

Could it be that i do some wrong encoding, and it understands the "wallet" it responds me with in the post message i make? Or it would throw other error in the case of wrong encodings?

**Comment by traderben** [comment]
It sounds like you are using your own .NET code and not this sdk?
That error means that a different user is being recovered based on the request and signature provided, which shouldn't happen if using an up to date version of this sdk. Feel free to join the hyperliquid discord to ask questions: https://discord.gg/hyperliquid
