### ISSUE TITLE
I want to query the transactions of address, how do I query it?

### ISSUE THREAD

**Issue by guoge310** [hyperliquid-dex/hyperliquid-python-sdk#72]
I know there are 2 ways
1. Scan based on blocks.
2. Scan based on address.

The relevant api interface cannot be found in the provided document.

Please help thanks.

Is there any tg or other contact information that you can share?

**Comment by traderben** [comment]
You can ask general questions in the api-traders channel of the discord: https://discord.gg/hyperliquid
