### ISSUE TITLE
New Rounding

### ISSUE THREAD

**Issue by lilelrain** [hyperliquid-dex/hyperliquid-python-sdk#74]
Hello! 
Writing regarding the recent API update: "based on user feedback, the tick formula will be updated on the next network upgrade to allow all integer prices regardless of number of sig figs. For example, after the change **123456 will be a valid price for BTC-USD**. The change is already live on testnet"

please, update [rounding.py](https://github.com/hyperliquid-dex/hyperliquid-python-sdk/blob/master/examples/rounding.py) in examples

`px = round(float(f"{px:.5g}"), 6)`

**Comment by traderben** [comment]
rounding.py was updated in this commit https://github.com/hyperliquid-dex/hyperliquid-python-sdk/commit/2e7abba40af2a755c06f3787e53da7491b8bf29c
