### ISSUE TITLE
spotUser action not work

### ISSUE THREAD

**Issue by hlongvu** [hyperliquid-dex/hyperliquid-python-sdk#76]
I tried to use this api: https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/exchange-endpoint#transfer-from-spot-account-to-perp-account-and-vice-versa

My request payload: {"action":{"type":"spotUser","classTransfer":{"usdc":1100000,"toPerp":true}},"nonce":1733910442843,"signature":{"r":"0xddef40cbaac1c2fa452afa28854e7a1eec2da7bf0e8aa04254ec8b863f5965fc","s":"0x13d147f843fddf3f2e8361ed8f1767631e86e25a0e274f1afd75ca12698e4031","v":27}} 

I got a respone of error 422: Failed to deserialize the JSON body into the target type

**Comment by traderben** [comment]
This is a repo for the python sdk, not the API in general. If you have a question about the API I recommend you join the discord and ask in api-traders. That endpoint no longer exists and has been replaced by usdClassTransfer. I'll update the docs
