### ISSUE TITLE
Multisig signer method ?

### ISSUE THREAD

**Issue by brendan-mccaffrey** [hyperliquid-dex/hyperliquid-python-sdk#77]
Looks to be dead code... perhaps it should be removed?

[Convert to multisig signer](https://github.com/hyperliquid-dex/hyperliquid-python-sdk/blob/master/examples/basic_convert_to_multi_sig_signer.py#L14)

**Comment by chameleon-jeff** [comment]
Good catch. The multisig spec was recently simplified. @lmlmt can you update the sdk?

**Comment by lmlmt** [comment]
This file is now removed from master and will be officially reflected in the upcoming release.
